import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Login system</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Welcome</h1>
      <p>
        Magna laborum occaecat sint pariatur Lorem nulla elit cupidatat veniam
        sint ea. Do ad magna ullamco enim sit labore officia ut pariatur Lorem
        cillum. Commodo ex aute tempor culpa. Amet laboris voluptate in nulla id
        minim eu sunt eu est labore qui. Et culpa consectetur irure eu proident
        in. Irure do id irure sint qui. Velit ea cupidatat sunt pariatur
        pariatur. Adipisicing proident enim consequat adipisicing Lorem velit
        magna. Consectetur ad eiusmod et laboris. Elit aliqua sit minim
        consectetur qui cupidatat anim laborum pariatur irure excepteur duis.
        Ipsum ea sunt nulla deserunt non qui voluptate voluptate tempor
        reprehenderit tempor officia est. Sit esse laboris velit minim commodo
        esse. Aliquip laborum cillum fugiat sint est irure occaecat anim elit
        veniam duis est. Aute ex ex adipisicing reprehenderit consequat irure
        aliquip. Veniam et non nisi reprehenderit do do. Qui commodo eiusmod ex
        sunt ipsum esse magna incididunt mollit eiusmod ullamco laboris. Mollit
        ex ipsum nulla enim velit sint Lorem laborum consequat dolore elit
        fugiat id Lorem. Voluptate in exercitation officia ullamco Lorem tempor.
        Lorem excepteur qui pariatur nulla incididunt aliquip ipsum voluptate
        quis consequat est. Ex proident nostrud laborum culpa amet qui qui et
        est nisi cupidatat anim deserunt. Consectetur velit ex minim cupidatat.
        Commodo dolor veniam proident ex irure aute occaecat aliquip. Velit esse
        irure elit anim.
      </p>
    </>
  );
}
